const WHATSAPP_NUMBER = "5519991166833";

const carIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M3 13.5 4.5 8a2 2 0 0 1 1.9-1.4h11.2A2 2 0 0 1 19.5 8l1.5 5.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M3 13.5h18v4a1 1 0 0 1-1 1h-1.5a1 1 0 0 1-1-1V16H6.5v1.5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-4Z" stroke-linecap="round" stroke-linejoin="round"/><circle cx="7" cy="16.5" r="1.4"/><circle cx="17" cy="16.5" r="1.4"/></svg>`;

const cars = [
  {
    id: "compass-limited-2021",
    marca: "Jeep",
    modelo: "Jeep Compass Limited 4x4 Diesel",
    tipo: "suv",
    ano: 2021,
    km: 42000,
    preco: 119990,
    blindado: false,
    cambio: "Automático",
    combustivel: "Diesel",
    cor: "Cinza",
    portas: 4,
    descricao: "Raridade com essa quilometragem à venda. Única dona, carro de procedência, com todas as revisões feitas na concessionária — revisão dos 40 mil km feita recentemente.",
    opcionais: ["Única dona", "Carro de procedência", "Todas as revisões na concessionária", "Completa", "Pneus novos", "Bancos em couro", "Banco elétrico do motorista"],
    fotos: ["assets/carros/compass-limited-2021-1.jpg", "assets/carros/compass-limited-2021-2.jpg"],
  },
  {
    id: "compass-longitude-2019",
    marca: "Jeep",
    modelo: "Jeep Compass Longitude 2.0",
    tipo: "suv",
    ano: 2019,
    km: 89000,
    preco: 89990,
    blindado: false,
    cambio: "Automático",
    combustivel: "Flex",
    cor: "Cinza",
    portas: 4,
    descricao: "Carro de procedência, única dona, completo. Som premium Beats e porta-malas de 410L.",
    opcionais: ["Única dona", "Som premium Beats", "Chave presencial", "Partida start/stop", "Bancos em couro", "Porta-malas de 410L"],
    fotos: ["assets/carros/compass-longitude-2019-1.jpg", "assets/carros/compass-longitude-2019-2.jpg"],
  },
  {
    id: "kicks-s-2019",
    marca: "Nissan",
    modelo: "Nissan Kicks S Direct 1.6 CVT",
    tipo: "suv",
    ano: 2019,
    km: 105000,
    preco: 77990,
    blindado: false,
    cambio: "Automático CVT",
    combustivel: "Flex",
    cor: "Cinza",
    portas: 4,
    descricao: "Ótimo carro para cidade e estrada, com excelente custo-benefício e economia de combustível.",
    opcionais: ["Ar-condicionado", "Direção elétrica", "Vidros elétricos", "Travas elétricas", "Retrovisor elétrico", "Airbag", "Freios ABS", "Alarme", "Volante com regulagem de altura"],
    fotos: ["assets/carros/kicks-s-2019-1.jpg", "assets/carros/kicks-s-2019-2.jpg"],
  },
  {
    id: "hilux-srv-2024",
    marca: "Toyota",
    modelo: "Toyota Hilux SRV 2.8 Cabine Dupla",
    tipo: "picape",
    ano: 2024,
    km: 25900,
    preco: 244990,
    blindado: false,
    cambio: "Automático",
    combustivel: "Diesel",
    cor: "Prata",
    portas: 4,
    descricao: "Caminhonete praticamente zero km, sem nenhum detalhe, ainda na garantia de fábrica (10 anos de garantia).",
    opcionais: ["Tração 4x4", "Na garantia de fábrica", "Completa"],
    fotos: ["assets/carros/hilux-srv-2024-1.jpg", "assets/carros/hilux-srv-2024-2.jpg"],
  },
  {
    id: "cruze-lt-2015",
    marca: "Chevrolet",
    modelo: "Chevrolet Cruze LT 1.8 Automático",
    tipo: "sedan",
    ano: 2015,
    km: 140000,
    preco: 59990,
    blindado: false,
    cambio: "Automático",
    combustivel: "Flex",
    cor: "Prata",
    portas: 4,
    descricao: "Único dono, 100% original de fábrica, completo e revisado.",
    opcionais: ["Único dono", "Bancos em couro", "100% original de fábrica", "Revisado"],
    fotos: ["assets/carros/cruze-lt-2015-1.jpg", "assets/carros/cruze-lt-2015-2.jpg"],
  },
  {
    id: "civic-lxs-2008",
    marca: "Honda",
    modelo: "Honda Civic LXS 1.8 Automático",
    tipo: "sedan",
    ano: 2008,
    km: 164000,
    preco: null,
    blindado: false,
    cambio: "Automático",
    combustivel: "Flex",
    cor: "Cinza",
    portas: 4,
    descricao: "Excelente carro, completo. Valor sob consulta — fale com a gente pelo WhatsApp.",
    opcionais: ["Completo"],
    fotos: ["assets/carros/civic-lxs-2008-1.jpg", "assets/carros/civic-lxs-2008-2.jpg"],
  },
  {
    id: "hb20-unique-2019",
    marca: "Hyundai",
    modelo: "Hyundai HB20 Unique 1.0",
    tipo: "hatch",
    ano: 2019,
    km: 112000,
    preco: 51990,
    blindado: false,
    cambio: "Manual",
    combustivel: "Flex",
    cor: "Branco",
    portas: 4,
    descricao: "Excelente carro, super econômico e revisado.",
    opcionais: ["Ar-condicionado", "Direção elétrica", "Airbag", "Freios ABS", "Som", "Vidros elétricos", "Travas elétricas", "Alarme"],
    fotos: ["assets/carros/hb20-unique-2019-1.jpg", "assets/carros/hb20-unique-2019-2.jpg"],
  },
  {
    id: "strada-endurance-2023",
    marca: "Fiat",
    modelo: "Fiat Strada Endurance 1.4",
    tipo: "picape",
    ano: 2023,
    km: 85000,
    preco: 71990,
    blindado: false,
    cambio: "Manual",
    combustivel: "Flex",
    cor: "Branco",
    portas: 2,
    descricao: "Cabine plus simples, completa, novíssima, sem nenhum detalhe. Carro usado apenas para passeio.",
    opcionais: ["Completa", "Sem detalhes"],
    fotos: ["assets/carros/strada-endurance-2023-1.jpg"],
  },
  {
    id: "fiat500-cult-2012",
    marca: "Fiat",
    modelo: "Fiat 500 Cult 1.4 Dualogic",
    tipo: "hatch",
    ano: 2012,
    km: 50800,
    preco: 45990,
    blindado: false,
    cambio: "Automatizado (Dualogic)",
    combustivel: "Flex",
    cor: "Cinza",
    portas: 2,
    descricao: "Raridade absoluta, placa final 6. Completo, revisado e com pneus novos.",
    opcionais: ["Raridade", "Completo", "Revisado", "Pneus novos"],
    fotos: ["assets/carros/fiat500-cult-2012-1.jpg", "assets/carros/fiat500-cult-2012-2.jpg"],
  },
  {
    id: "c3-tendance-2014",
    marca: "Citroën",
    modelo: "Citroën C3 Tendance 1.5",
    tipo: "hatch",
    ano: 2014,
    km: 122000,
    preco: 39990,
    blindado: false,
    cambio: "Manual",
    combustivel: "Flex",
    cor: "Vermelho cereja",
    portas: 4,
    descricao: "Completo, revisado, pneus novos, bancos bicolor e para-brisa panorâmico.",
    opcionais: ["Pneus novos", "Revisado", "Rodas de liga leve", "Bancos bicolor", "Para-brisa panorâmico"],
    fotos: ["assets/carros/c3-tendance-2014-1.jpg", "assets/carros/c3-tendance-2014-2.jpg"],
  },
  {
    id: "yzf-r3-monster-2021",
    marca: "Yamaha",
    modelo: "Yamaha YZF R3 Monster",
    tipo: "moto",
    ano: 2021,
    km: 11500,
    preco: 25990,
    blindado: false,
    cambio: "Manual",
    combustivel: "Gasolina",
    cor: "Preta",
    portas: 0,
    descricao: "Edição especial Monster, 300cc, em excelente estado de conservação.",
    opcionais: ["Edição especial Monster", "300cc"],
    fotos: ["assets/carros/yzf-r3-monster-2021-1.jpg", "assets/carros/yzf-r3-monster-2021-2.jpg"],
  },
];

const MARCAS_DISPONIVEIS = [
  "Acura", "Agrale", "Alfa Romeo", "Asia Motors", "Aston Martin", "Audi",
  "BMW", "BYD", "Cadillac", "Chery", "Chevrolet", "Chrysler", "Citroën",
  "Dodge", "Effa", "Ferrari", "Fiat", "Ford", "Foton", "GWM", "Honda", "Hyundai",
  "Iveco", "JAC", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus",
  "Lifan", "Lotus", "Mahindra", "Maserati", "Mercedes-Benz", "MINI", "Mitsubishi",
  "Nissan", "Peugeot", "Porsche", "RAM", "Renault", "Rolls-Royce", "Smart",
  "SsangYong", "Subaru", "Suzuki", "Toyota", "Troller", "Volkswagen", "Volvo", "Yamaha",
];

const formatKm = (km) => `${km.toLocaleString("pt-BR")} km`;
const formatPreco = (preco) => (preco == null ? "Sob consulta" : preco.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }));
const getCarById = (id) => cars.find((c) => c.id === id);
